# Schema for data processing configuration
# All fields are optional and will use defaults if not specified

# Time handling configuration
time_column: time # Default column name for timestamps
time_format: "%Y-%m-%d" # Python strftime format
timezone: UTC # Timezone for datetime operations

# File output configuration
separator: "," # CSV separator character

# Advanced save configuration
save:
    type: csv # Possible values: csv, parquet, feather, json
    compression: infer # Compression options: ['infer', '', 'bz2', 'gzip', 'tar', 'xz', 'zip', 'zstd']

# Column name sanitization
special_symbols:
    patterns: [" ", "-", "(", ")", "/", ".", "[", "]"] # Symbols to replace
    replacement: "_" # Character to use as replacement

# Data type configuration
numeric_precision: float64 # Possible values: float32, float64, int32, int64
