# See - https://www.influxdata.com/blog/running-influxdb-2-0-and-telegraf-using-docker/
networks:
    default:
        driver: bridge

services:
    mlflow:
        image: ghcr.io/mlflow/mlflow:latest
        container_name: mlflow
        restart: unless-stopped
        ports:
            - "5000:5000"
        volumes:
            - ./mlruns:/mlruns:Z
        command: >
            bash -c "
            mlflow server
            --host 0.0.0.0
            --port 5000"
