version: "3.0"

volumes:
    influxdb_beta:

services:
    influxdb_beta:
        image: quay.io/influxdb/influxdb:2.0.0-beta

        ports:
            - 9999:9999

        volumes:
            - ./influxdbv2:/root/.influxdbv2

        healthcheck:
            test: influx setup -f -o Polaris -t vinvelivaanilai_token -u polaris_admin -p polaris_admin -b DockerStats -r 0
