name: Check

on:
    push:
        branches: ["main"]
        paths-ignore:
            - "readme.md"
            - "license.md"
            - "img/**"
            - "docker/**"
            - ".github/CODE_OF_CONDUCT.md"
            - ".github/SECURITY.md"
    pull_request:
        branches: ["main"]
    workflow_dispatch:

jobs:
    setup:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Set up Python 3.13
              uses: actions/setup-python@v5
              with:
                  python-version: 3.13
                  cache: "pip"
                  cache-dependency-path: pyproject.toml

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install ".[dev]"

    pytest:
        runs-on: ubuntu-latest
        needs:
            - setup
        steps:
            - name: Test with pytest
              run: |
                  pytest --cov=astra --cov-report=html --cov-report=term-missing

            - name: Upload coverage reports
              uses: codecov/codecov-action@v5
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}

            - name: Upload test artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: tests-artifacts
                  path: |
                      tests/artifacts
                      htmlcov/
                      .coverage

    ruff:
        runs-on: ubuntu-latest
        needs:
            - setup
        steps:
            - name: Lint and fix with Ruff
              run: |
                  ruff check --fix --exit-non-zero-on-fix .

    pylint:
        runs-on: ubuntu-latest
        needs:
            - setup
        steps:
            - name: Lint and fix with pylint
              run: |
                  pylint $(git ls-files '*.py')

    black:
        runs-on: ubuntu-latest
        needs:
            - setup
        steps:
            - name: Format with black
              run: |
                  black --check --diff .
