name: check

on:
    push:
        branches: ["main"]
        paths-ignore:
            - "readme.md"
            - "license.md"
            - "img/**"
            - "docker/**"
            - ".github/CODE_OF_CONDUCT.md"
            - ".github/SECURITY.md"
    pull_request:
        branches: ["main"]
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: setup_python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.13"
                  cache: "pip"
                  cache-dependency-path: pyproject.toml

            - name: install_deps
              run: |
                  python -m pip install --upgrade pip
                  pip install ".[dev]"

            - name: run_pytest
              run: pytest --cov=astra --cov-report=html --cov-report=term-missing

            - name: upload_coverage
              uses: codecov/codecov-action@v5
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}

            - name: upload_test_artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: test-artifacts
                  path: |
                      tests/artifacts
                      htmlcov/
                      .coverage

    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: setup_python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.13"
                  cache: "pip"
                  cache-dependency-path: pyproject.toml

            - name: install_deps
              run: |
                  python -m pip install --upgrade pip
                  pip install ".[dev]"

            - name: run_ruff
              run: ruff check --fix --exit-non-zero-on-fix .

            - name: run_pylint
              run: pylint $(git ls-files '*.py')

            - name: run_black
              run: black --check --diff .

            - name: run_mypy
              run: mypy astra
