name: Publish Python Package

on:
    push:
        tags:
            - "*"

jobs:
    build:
        name: Build distribution 📦
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.13"
            - name: Install build dependencies
              run: python -m pip install build --user
            - name: Build package
              run: python -m build
            - name: Store the distribution packages
              uses: actions/upload-artifact@v4
              with:
                  name: python-package-distributions
                  path: dist/

    publish-to-github:
        name: Publish to GitHub Packages
        needs: build
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Download all the dists
              uses: actions/download-artifact@v4
              with:
                  name: python-package-distributions
                  path: dist/
            - name: Create GitHub Release
              env:
                  GITHUB_TOKEN: ${{ github.token }}
              run: >-
                  gh release create
                  "$GITHUB_REF_NAME"
                  --repo "$GITHUB_REPOSITORY"
                  --notes ""
