name: ci/cd assurance pipeline

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]
    workflow_dispatch:

jobs:
    test:
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, windows-latest]
                python-version: ["3.13"]

        runs-on: ${{ matrix.os }}

        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.python-version }}
                  cache: "pip"
                  cache-dependency-path: pyproject.toml

            - name: Install dependencies
              run: |
                  pip install ".[dev]"

            - name: Lint with black
              run: |
                  black --check --diff .

            - name: Test with pytest
              run: |
                  pytest --cov=astra --cov-report=xml

            - name: Upload coverage reports
              uses: codecov/codecov-action@v5
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
              if: matrix.os == 'ubuntu-latest'

            - name: Upload test artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: test-artifacts-${{ matrix.os }}-${{ matrix.python-version }}
              path: |
                  test/artifacts
                  test_results.xml
                  .coverage
